#!/bin/bash
# 本脚本用于安全，快捷的登录
source <(ssh-agent) && ssh-add ~/.ssh/id_rsa
ssh -o connecttimeout=1 -At ${@} "$(cat <<'EOF'
echo '
termcapinfo xterm* ti@:te@ 
escape ^Ss 
altscreen on 
vbell off 
maptimeout 0 
defc1 off 
caption always "(Jssh) %c:%s %D %Y%m%d%{= dd} %-Lw%45L>%{+bu}%n %t%{-}%+Lw%-09< %="
shell bash 
shelltitle "$ |bash"
' > ~/.screenrc
screen -d A;
rm ~/.ssh/ssh_auth_sock;
echo $SSH_AUTH_SOCK;
ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock; 
grep jssh ~/.bashrc || echo "
#jssh
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
test x\$TERM = xscreen &&
    stty stop '' &&
    PROMPT_COMMAND='echo -ne \"\\033k\$(basename \$(pwd))\\033\\\\\"'
" >> ~/.bashrc

screen -dRR;
EOF
)"
